githubschool/apr-16

README.md
_posts/0000-01-07-RadaKichenin.md

This is test amendment for TTT program
githubteacher, please review ..

Modified line no 2 on README file

---

_posts/0000-01-03-hitochan777.md

This PR is in relation to #4.
@brianamarie please review!

Change caption on hitochan777's file

---

_posts/0000-01-11-githubteacher.md

This pull request changes the caption to @githubteacher's file for the class activity. 
This pull request is in relation to #4. 
@brianamarie could you please review? 
This will be complete when....

Change caption on githubteacher's file

---

_posts/0000-01-10-suwa-yuki.md

This PR changes the caption to @suwa-yuki 's file for the class activity.
Relation to #4 .

Change caption on suwa-yuki's file

---

_posts/0000-01-11-nekia.md

This change include a change of image's caption.
This PR is in relation to #9 
This issue will complete when the followings are satisfied

Change caption on nekia's file

---

_posts/0000-01-06-sskhk.md

Change the caption to my name.
@brianamarie Could you review my code ?

change caption

---

_posts/0000-01-12-prayuja-patil.md

This pull request changes the caption.

caption changed

---

_posts/0000-01-08-f14d.md

This pull request changes the caption on f14d's file for the class activity.
@brianamarie could you please review?

Change caption on f14d's file

---

_posts/0000-01-05-kut-arika.md

This pull request changes the caption to @kut-arika's file for the class activity.

Change caption on kut-arika file

---

_posts/0000-01-11-githubteacher.md
_posts/0000-01-18-shimazaki-yoshiyuki.md

This PR changes the caption to  @githubteacher `s file .
This Pull Request is in reation to #4.

change githuteacher.md by yoshiyuki

---

_posts/0000-01-09-hirofu.md

:octocat: 
this pull request is relation to #4.

add my caption on hirofu-add-caption

---

_posts/0000-01-04-arugupta.md

This pull request changes the caption @githubteacher /ARUGUPTA for the class activity.
This pull request is in relation to #4

Aradhana's change in Caption file

---

_posts/0000-01-19-hideakikondo.md

change caption on hideakikondo's file

---

_posts/0000-01-01-intro.md
_posts/fssl.txt

Fssl conflict 3

---

_posts/0000-01-11-nekia.md

This PR changes neki's caption title.

Change neki's caption

---

_posts/0000-01-05-kut-arika.md

kut-arika のスライドを編集しました

---

_posts/0000-01-03-hitochan777.md

Edit caption for hitochan777

---

_posts/0000-01-11-nekia.md

Based on following reason, changed the caption.
- Out of date
- Not funny

Change to proper caption for the image

---

_posts/0000-01-13-rajansinghal.md

changing caption for rajan under _post fir @brianamarie 
#64

changing caption in _posts dir for rajan

---

_posts/0000-01-13-rajansinghal.md

this file contains changes to caption 
close #28

changing caption in 

---

_posts/0000-01-18-shimazaki-yoshiyuki.md

update 0000-01-18-shimazaki-yoshiyuki.md
@githubteacher

change 0000-01-18-shimazaki-yoshiyuki.md
